config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'

  namespace 'course' do
    get '', to: 'theory#index'

    resources :task_sets, only: [:show] do
      member do
        post 'submit', to: 'task_sets#submit'
      end
    end
    resources :theory, only: [:index, :show]
  end

  resources :exams do
    member do
      post 'start', to: 'exams#start', as: :start
      post 'stop', to: 'exams#stop', as: :stop
    end

    with_options module: 'exams' do
      resources :links, only: [:index]
      resources :tasks, only: [:index]
      resources :submissions, only: [:create]
      resources :examinees, only: [:show]
    end
  end

  resources :exam_sessions, only: [:show, :new, :create, :destroy], module: 'exams', controller: 'sessions'

  resources :join, only: [:show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contacts
  end
end

app/views/static_pages/about.html.erb
<div class="container-fluid d-flex flex-column justify-content-center w-100 h-100 bg-dark text-light">
  <div class="align-self-center text-justify" style="max-width: 80ch">
    <h1 class="text-center">О проекте</h1>

    <p>Основное назначение данного ЭОР на текущий момент – информационная поддержка курса «Развитие элементов вычислительной культуры младших школьников», в частности, наибольшее внимание уделено теме «Обучение младших школьников рационализации вычислений».</p>

    <p>В дальнейшем список курсов планируется дополнить.</p>
  </div>
</div>

app/views/static_pages/contacts.html.erb
<div class="container-fluid d-flex flex-column justify-content-center w-100 h-100 bg-dark text-light">
  <div class="align-self-center" style="max-width: 80ch">
    <h1>Контакты</h1>

    <p><i class="fas fa-user"></i> Ивашов А.Ю.</p>

    <p>
      <i class="fas fa-at"></i>
      <a class="text-light" href="mailto:anton.ivashof@gmail.com">anton.ivashof@gmail.com</a>
    </p>

    <p>
      <i class="fas fa-mobile-alt"></i> <a class="text-light" href="tel:+79043310340">+7 (904) 331-03-40</a>
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid d-flex flex-column justify-content-center w-100 h-100 bg-dark text-light">
  <main class="mx-auto py-3" style="max-width: 80ch" role="main">
    <h1 class="display-4">RatioCalc</h1>
    <p class="lead">Научись учить детей рационализации вычислений!</p>
    <hr class="my-4" style="border-color: inherit">
    <p>Сайт представляет собой бесплатный интерактивный курс по методике обучения детей начальной школы техникам рационализации вычислений. В рамках курса доступны теоретические материалы и практические задания для самопроверки, а также контрольное прохождение заданий для проверки преподавателем</p>
    <a class="btn btn-primary btn-lg" href="<%= course_path %>" role="button">Перейти к курсу</a>
  </main>
</div>