config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'

  namespace 'course' do
    get '', to: 'theory#index'

    resources :task_sets, only: [:show] do
      member do
        post 'submit', to: 'task_sets#submit'
      end
    end
    resources :theory, only: [:index, :show]
  end

  resources :exams do
    member do
      post 'start', to: 'exams#start', as: :start
      post 'stop', to: 'exams#stop', as: :stop
    end

    with_options module: 'exams' do
      resources :links, only: [:index]
      resources :tasks, only: [:index]
      resources :submissions, only: [:create]
      resources :examinees, only: [:show]
    end
  end

  resources :exam_sessions, only: [:show, :new, :create, :destroy], module: 'exams', controller: 'sessions'

  resources :join, only: [:show]
end

app/views/partials/components/_back_navigation.html.erb
<div class="back-navigation">
  <a href="<%= back_url %>" class="back-navigation__back-btn">
    <i class="back-navigation__back-icon"></i>
    Назад
  </a>
</div>

app/views/partials/components/_collapse_card.html.erb
<% id = "collapse-card__collapse-#{SecureRandom.hex(8)}" %>

<div class="collapse-card">
  <div class="collapse-card__card-header">
    <button class="collapse-card__collapse-btn"
       type="button"
       data-toggle="collapse"
       data-target="#<%= id %>"
       aria-expanded="true"
       aria-controls="<%= id %>"
    >
      <i class="fas fa-sort text-dark"></i>
      <%= title %>
    </button>
  </div>

  <div id="<%= id %>" class="collapse">
    <div class="collapse-card__body">
      <%= render "contents/#{content_id}" %>
    </div>
  </div>
</div>

app/views/partials/components/_exam_links.html.erb
<div class="exam-links">
  <div class="exam-links__container">
    <div class="exam-links__qr-code">
      <%= qr_code(join_url(exam.session_token)) %>
    </div>
    <div class="exam-links__info">
      <h1><%= exam.title %></h1>
      <h3><%= exam.task_set.title %></h3>
      <h4><%= link_to(join_url(exam.session_token), join_url(exam.session_token)) %></h4>
    </div>
  </div>
</div>

app/views/partials/components/_exams_list.html.erb
<div class="exams-list">
  <div class="exams-list__header">
    <div class="exams-list__page-title">
      <h1>
        Контроль
        <span class="float-right">
          <a class="exams-list__create-exam-btn" href="<%= new_exam_path %>">
            <i class="exams-list__plus-icon"></i>
            Создать
          </a>
        </span>
      </h1>
    </div>
  </div>

  <div class="exams-list__content">
    <div class="exams-list__table-container">
      <table class="exams-list__table">
        <thead class="exams-list__table-header">
          <tr>
            <th scope="col">Дата</th>
            <th scope="col">Название</th>
            <th scope="col">Тема</th>
            <th scope="col">Статус</th>
            <th scope="col">Действия</th>
          </tr>
        </thead>

        <tbody class="exams-list__table-body">
          <% exams.each do |exam| %>
            <tr>
              <th scope="row">
                <%= exam.started_at&.strftime("%d.%m.%y %H:%M") %>
              </th>
              <td><%= exam.title %></td>
              <td><%= exam.task_set.title %></td>
              <td>
                <span class="exams-status-badge exams-status-badge--<%= exam.status %>">
                  <%= t(exam.status, scope: 'models.exam.status') %>
                </span>
              </td>
              <td>
                <a class="exams-list__show-btn" href="<%= exam_url(exam.id) %>">
                  <i class="exams-list__eye-icon"></i>
                </a>
                <a class="exams-list__edit-btn" href="<%= edit_exam_url(exam.id) %>">
                  <i class="exams-list__pencil-icon"></i>
                </a>
                <%=
                  link_to(
                    exam_path(exam),
                    method: :delete,
                    class: <<~CLASS,
                      exams-list__delete-btn
                      #{'exams-list__delete-btn--disabled' if exam.ongoing?}
                    CLASS
                    data: { confirm: 'Вы уверены?' }
                  ) do
                %>
                  <i class="exams-list__trash-icon"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/partials/components/_footer.html.erb
<div class="footer">
  <div class="footer__row">
    <div class="footer__content-col">
      Ивашов А.Ю., 2019 г.
    </div>

    <div class="footer__auth-controls-col">
      <% if user_signed_in? %>
        <%= render 'partials/components/sign_out_controls', user: current_user.email %>
      <% else %>
        <%= render 'partials/components/sign_in_controls' %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/components/_main_navbar.html.erb
<nav class="main-navbar">
  <a class="main-navbar__brand-link" href="<%= root_url %>">RatioCalc</a>

  <button class="main-navbar__toggler-btn"
          type="button"
          data-toggle="collapse"
          data-target=".main-navbar__collapse"
          aria-controls="main-navbar__collapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
  >
    <span class="main-navbar__toggler-btn-icon"></span>
  </button>

  <div class="main-navbar__collapse collapse">
    <div class="main-navbar__nav">
      <%
        [
          ['Материалы', course_path],
          (['Контроль',  exams_path] if user_signed_in?),
          ['О проекте', about_path],
          ['Контакты', contacts_path],
        ].compact.each do |title, url|
      %>
        <a class="main-navbar__nav-link" href="<%= url %>">
          <span class="main-navbar__nav-link-text
                       <%= 'main-navbar__nav-link-text--active' if request.path =~ /#{url}/ %>">
            <%= title %>
          </span>
        </a>
      <% end %>
    </div>
  </div>
</nav>

app/views/partials/components/_section_navigation.html.erb
<div class="section-navigation">
  <div class="section-navigation__row">
    <div class="section-navigation__col">
      <a class="section-navigation__btn
                <%= 'section-navigation__btn--invisible' unless course_progress.prev? %>"
         href="<%= course_progress.prev_url %>"
      >
        <i class="section-navigation__icon-back"></i>
      </a>

      <span class="section-navigation__text">
        Часть <%= course_progress.step_number %> из <%= course_progress.steps_count %>
      </span>

      <a class="section-navigation__btn
                <%= 'section-navigation__btn--invisible' unless course_progress.next? %>"
         href="<%= course_progress.next_url %>"
      >
        <i class="section-navigation__icon-forvard"></i>
      </a>
    </div>
  </div>
</div>

app/views/partials/components/_sections_menu.html.erb
<nav class="sections-menu">
  <h6 class="sections-menu__header">1. Рационализация вычислительной программы</h6>

  <ul class="sections-menu__nav">
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('1-1')) %>"
         href="<%= course_theory_path('1-1') %>"
      >
        Преобразование выражений
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_task_set_path(1)) %>"
         href="<%= course_task_set_path(1) %>"
      >
        └─ Практика
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('1-2')) %>"
         href="<%= course_theory_path('1-2') %>"
      >
        Невыполнение действий
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_task_set_path(2)) %>"
         href="<%= course_task_set_path(2) %>"
      >
        └─ Практика
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('1-3')) %>"
         href="<%= course_theory_path('1-3') %>"
      >
        Усложнение  условий
      </a>
    </li>
  </ul>

  <h6 class="sections-menu__header">2. Методика обучения младших школьников рационализации вычислений</h6>

  <ul class="sections-menu__nav">
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('2-1')) %>"
         href="<%= course_theory_path('2-1') %>"
      >
        Общая информация
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('2-2')) %>"
         href="<%= course_theory_path('2-2') %>"
      >
        Этап 1: Усвоение теории арифметических действий
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('2-3')) %>"
         href="<%= course_theory_path('2-3') %>"
      >
        Этап 2: Сокращение помощи учителя, усвоение новых теоретических знаний
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_theory_path('2-4')) %>"
         href="<%= course_theory_path('2-4') %>"
      >
        Этап 3: Самостоятельный поиск удобных способов вычислений
      </a>
    </li>
    <li class="sections-menu__nav-item">
      <a class="sections-menu__link
                <%= 'sections-menu__link--active' if current_page?(course_task_set_path(3)) %>"
         href="<%= course_task_set_path(3) %>"
      >
        └─ Практика
      </a>
    </li>
  </ul>
</nav>

app/views/partials/components/_sign_in_controls.html.erb
<div class="sign-in-controls">
  <a class="sign-in-controls__sign-in-btn" href="<%= new_user_session_path %>">
    <i class="sign-in-controls__sign-in-icon"></i>
    Вход
  </a>
</div>

app/views/partials/components/_sign_out_controls.html.erb
<div class="sign-out-controls">
  <span class="sign-out-controls__username">
    <i class="sign-out-controls__user-icon"></i>
    <%= user %>
  </span>

  <%= link_to destroy_user_session_path, method: :delete, class: "sign-out-controls__sign-out-btn" do %>
    Выход
    <i class="sign-out-controls__sign-out-icon"></i>
  <% end %>
  </a>
</div>

app/views/partials/components/_task.html.erb
<div class="task">
  <div class="task__header">
    <div class="task__description-container">
      <div class="task__description"><%= task.description %></div>
    </div>
  </div>

  <% if task.contents %>
    <div class="task__body">
      <div class="task__contents">
        <hr />
        <%= raw task.contents %>
        <hr />
      </div>
    </div>
  <% end %>

  <div class="task__footer">
    <%= render 'partials/components/task_controls', task: task, event: event, submission: submission, mode: mode %>
  </div>
</div>

app/views/partials/components/_task_controls.html.erb
<%=
  form_for(
    'submission',
    method: :post,
    url: event.is_a?(Exam) ? exam_submissions_path(event.id) : submit_course_task_set_path(event.id),
    html: { class: "task-controls" }
  ) do |f|
%>
  <%= f.hidden_field :task_id, value: task.id %>
  <div class="task-controls__inputs">
    <% if task.multiple_choice? %>
      <%= render 'partials/components/task_controls/multiple_choice', options: task.options, submission: submission, mode: mode %>
    <% elsif task.single_input? %>
      <%= render 'partials/components/task_controls/single_input', hint: task.hint, submission: submission, mode: mode %>
    <% end %>
  </div>

  <% if !event.is_a?(Exam) && submission && %[correct incorrect].include?(submission.status) %>
    <div class="task-controls__status">
      <%= submission.status == 'correct' ? 'Верно!' : 'Неверно!' %>
    </div>
  <% end %>

  <% if mode == :solve %>
    <div class="task-controls__submit">
      <button type="submit" class="task-controls__submit-btn">
        <%= event.is_a?(Exam) ? 'Отправить' : 'Проверить' %>
      </button>
    </div>
  <% end %>
<% end %>

app/views/partials/components/_task_set.html.erb
<div class="task-set">
  <div class="task-set__header">
    <div class="task-set__task-selector">
      <%= render 'partials/components/task_set/task_selector',
                 tasks: tasks,
                 current_task_id: current_task.id %>
    </div>
  </div>

  <div class="task-set__body">
    <div class="task-set__task
                <%= "task-set__task--#{submission.status}" if !event.is_a?(Exam) && submission %>">
      <%= render 'partials/components/task', task: current_task, event: event, submission: submission, mode: :solve %>
    </div>
  </div>

  <div class="task-set__footer">
    <div class="task-set__navigation">
      <%
        task_ids = tasks.map { |task| task[:id] }
        current_index = task_ids.index(current_task.id)

        prev_id = current_index - 1 >= 0 ? task_ids[current_index - 1] : nil
        next_id = current_index + 1 < tasks.size ? task_ids[current_index + 1] : nil
      %>
      <%= render 'partials/components/task_set/navigation',
                 prev_url: prev_id ? "?tid=#{prev_id}" : nil,
                 next_url: next_id ? "?tid=#{next_id}" : nil %>
    </div>
  </div>
</div>

app/views/partials/components/_theory.html.erb
<div class="theory">
  <div class="theory__layout-row">
    <div class="theory__layout-col">
      <%= render "contents/#{content_id}" %>
    </div>
  </div>
</div>