config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'

  namespace 'course' do
    get '', to: 'theory#index'

    resources :task_sets, only: [:show] do
      member do
        post 'submit', to: 'task_sets#submit'
      end
    end
    resources :theory, only: [:index, :show]
  end

  resources :exams do
    member do
      post 'start', to: 'exams#start', as: :start
      post 'stop', to: 'exams#stop', as: :stop
    end

    with_options module: 'exams' do
      resources :links, only: [:index]
      resources :tasks, only: [:index]
      resources :submissions, only: [:create]
      resources :examinees, only: [:show]
    end
  end

  resources :exam_sessions, only: [:show, :new, :create, :destroy], module: 'exams', controller: 'sessions'

  resources :join, only: [:show]
end

app/views/partials/pages/_exam_change_page.html.erb
<div class="exam-change-page">
  <div class="exam-change-page__content-row">
    <div class="exam-change-page__content-col">
      <div class="exam-change-page__form-container">
        <div class="exam-change-page__form-container-header">
          <% action_name = exam.new_record? ? 'Создание' : 'Изменение' %>
          <h1 class="exam-change-page__heading"><%= action_name %> сессии контроля</h1>
        </div>
        <div class="exam-change-page__form-container-body">
          <%= render 'partials/components/exams/exam_form', exam: exam %>
        </div>
      </div>

      <div class="exam-change-page__navigation-row">
        <div class="exam-change-page__navigation-col">
          <%= render 'partials/components/back_navigation', back_url: exams_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/pages/_exam_page.html.erb
<div class="exam-page">
  <div class="exam-page__row">
    <div class="exam-page__details">
      <div class="exam-page__header-row">
        <h1 class="exam-page__header"><%= exam.title %></h1>
      </div>

      <div class="exam-page__controls-row">
        <div class="exam-page__controls-col">
          <%= render 'partials/components/exams/exam_status_controls', exam: exam %>
        </div>
      </div>

      <div class="exam-page__details-row">
        <div class="exam-page__details-col">
          <%= render 'partials/components/exams/exam_details', exam: exam %>
        </div>
      </div>

      <div class="exam-page__navigation-row">
        <div class="exam-page__navigation-col">
          <%= render 'partials/components/back_navigation', back_url: exams_path %>
        </div>
      </div>
    </div>

    <div class="exam-page__results">
      <div class="exam-page__results-header-row">
        <h2 class="exam-page__results-header">
          Результаты
          <span class="exam-page__results-controls">
            <a href="<%= request.path %>" class="exam-page__reload-results-btn">
              <i class="exam-page__sync-icon"></i>
            </a>
          </span>
        </h2>
      </div>

      <%= render 'partials/components/exams/results_table', exam: exam %>
    </div>
  </div>
</div>

app/views/partials/pages/_exam_session_page.html.erb
<div class="exam-session-page">
  <div class="exam-session-page__row">
    <div class="exam-session-page__content-col">
      <% if examinee %>
        <%= render 'partials/components/exams/exam_session_username_check',
                   token: token, username: examinee.username, exam_id: exam_id %>
      <% else %>
        <%= render 'partials/components/exams/exam_session_form', token: token %>
      <% end %>
    </div>
  </div>
</div>